apiVersion: v1
kind: Service
metadata:
  name: nodeapp
  namespace: production
  labels:
    app: nodeapp
spec:
  type: LoadBalancer
  selector:
    app: nodeapp
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
